version: "3"

services:
    traefik:
        image: traefik:v2.0
        command: 
            - "--api.insecure=true" 
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
        ports: 
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - public
            - internal
    lookup:
        build: lookup/.
        networks:
            - internal
    mongo:
        image: mongo
        networks: 
            - internal
    user_mgmt:
        build: user_mgmt/.
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.lookup.rule=Host(`localhost`)"
            - "traefik.http.routers.lookup.entrypoints=web"
            - "traefik.port=1323"
        depends_on:
            - mongo
        networks:
            - internal

networks:
   public:
   internal: