name: testing deployment workflows
on:
  deployment:
    environment: production

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: print info
        run: |
          echo "${{ github.GITHUB_EVENT_NAME }}"
          echo "${{ github.GITHUB_EVENT_PATH }}"
