name: testing deployment workflows
on:
  deployment:
    environment: production

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.deployment) }}
        run: echo "$GITHUB_CONTEXT"
