name: testing deployment workflows
on:
  deployment:
    environment: production

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: print info
        run: |
          echo ${ event_name }
          echo ${ event_path }
        env:
          event_name: ${{ github.GITHUB_EVENT_NAME }}
          event_path: ${{ github.GITHUB_EVENT_PATH }}
