name: testing deployment workflows
on:
  deployment:
    environment: production

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: print info
        run: |
          python3 -c print(${{ github.GITHUB_EVENT_NAME }})
          python3 -c print(${{ github.GITHUB_EVENT_PATH }})
